version: '3.2'

services:
  db:
    container_name: db
    hostname: db
    image: postgres:${POSTGRES_VERSION}
    restart: always
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres_db
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
    networks:
      - backend
      - frontend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres_user -d postgres_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    container_name: app
    hostname: app
    image: nextcloud:${NEXTCLOUD_VERSION}
    restart: always
    ports:
      - 127.0.0.1:9000:9000
    volumes: &nextcloud_vol
      - /mnt/nextcloud-dp/nextcloud:/var/www/html
      - /mnt/nextcloud-dp/php-settings:/usr/local/etc
      - ./crontab:/var/spool/cron/crontabs/www-data:ro
      #- ./secrets/redis_password.txt:/run/secrets/redis_password
    environment: &nextcloud_env
      - POSTGRES_HOST=db
      - POSTGRES_DB=postgres_db
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
      - NEXTCLOUD_ADMIN_PASSWORD=nextcloud_admin_password
      - NEXTCLOUD_ADMIN_USER=nextcloud_admin_user
      - VIRTUAL_HOST=${NEXTCLOUD_VIRTUAL_HOST}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_VIRTUAL_HOST}
      - REDIS_HOST=redis
      - ALLOWED_FRAME_DOMAIN=${ALLOWED_FRAME_DOMAIN}
      #- REDIS_HOST_PASSWORD=/run/secrets/redis_password
    depends_on: &nextcloud_dep
      - db
      - redis
    networks: &nextcloud_net
      - backend
      - frontend
      - keycloak

  cron:
    container_name: cron
    hostname: cron
    build:
     context: ./nextcloud
     args:
      - NEXTCLOUD_VERSION=${NEXTCLOUD_VERSION}
    restart: always
    volumes: *nextcloud_vol
    environment: *nextcloud_env
    depends_on: 
      - db
      - redis
      - app
    networks: *nextcloud_net
    entrypoint: ['/usr/bin/supervisord', '-c', '/supervisord.conf']
  
  sociallogin_init:
    container_name: sociallogin_init
    restart: on-failure
    image: nextcloud:${NEXTCLOUD_VERSION}
    volumes: 
      # - <<: *nextcloud_vol
      - /mnt/nextcloud-dp/nextcloud:/var/www/html
      - /mnt/nextcloud-dp/php-settings:/usr/local/etc
      - ./crontab:/var/spool/cron/crontabs/www-data:ro
      - ./add_custom_provider.sh:/add_custom_provider.sh
    environment:
      - NEXTCLOUD_ADMIN_PASSWORD=nextcloud_admin_password
      - NEXTCLOUD_ADMIN_USER=nextcloud_admin_user
      - VIRTUAL_HOST=${NEXTCLOUD_VIRTUAL_HOST}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_VIRTUAL_HOST}
      - BASE_URL=${IAM_BASE_URL}
      - BASE_EXTERNAL_URL=${IAM_BASE_EXTERNAL_URL}
      - REALM_NAME=hip
      - CLIENT_ID=hip
      - CLIENT_SECRET=supersecret
      - GROUP_NAME=hip
      - GROUP_NC_NAME=hip
    user: www-data
    depends_on: *nextcloud_dep
    networks: *nextcloud_net
    entrypoint: ['/add_custom_provider.sh']

  redis:
    container_name: redis
    hostname: redis
    image: redis:latest
    #environment:
    #  - REDIS_HOST_PASSWORD=/run/secrets/redis_password
    #command: bash -c '[ "$$REDIS_HOST_PASSWORD" ] &&
    #  ( cat "$$REDIS_HOST_PASSWORD" | xargs redis-server --appendonly yes --requirepass)' #|| redis-server --appendonly yes'
    command: redis-server --appendonly yes
    restart: always
    volumes:
      - ./redis/data:/data
    #  - ./secrets/redis_password.txt:/run/secrets/redis_password
    networks:
      - backend

  # caddy:
  #   container_name: caddy
  #   image: caddy:latest
  #   restart: always
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./caddy/Caddyfile:/etc/caddy/Caddyfile

  #     - ./caddy/caddy_data:/data
  #     - /mnt/nextcloud-dp/nextcloud:/var/www/html
  #   networks:
  #     - backend


networks:
  frontend:
    driver: bridge
    # driver_opts:
    #   com.docker.network.driver.mtu: 1450
  backend:
    internal: true
  keycloak:
    name: keycloak
